export const areas = [
  {
    id: 'shibuya',
    name: '东京都涩谷区',
    ward: 'Shibuya City',
    neighborhood: '神南 1 丁目',
    sourceUpdatedAt: '2026-05-10',
    collectionPoint: '公寓一层后门右侧绿色收集网',
  },
  {
    id: 'shinjuku',
    name: '东京都新宿区',
    ward: 'Shinjuku City',
    neighborhood: '西新宿 2 丁目',
    sourceUpdatedAt: '2026-05-08',
    collectionPoint: '入口左侧停车位旁指定垃圾区',
  },
  {
    id: 'minato',
    name: '东京都港区',
    ward: 'Minato City',
    neighborhood: '赤坂 3 丁目',
    sourceUpdatedAt: '2026-05-12',
    collectionPoint: '建筑物后侧蓝色资源回收箱区域',
  },
]

export const areaText = {
  shibuya: {
    ja: {
      name: '東京都渋谷区',
      collectionPoint: 'マンション 1 階裏口右側の緑色収集ネット',
    },
    en: {
      name: 'Shibuya City, Tokyo',
      collectionPoint: 'Green collection net on the right side of the ground-floor rear entrance',
    },
    ko: {
      name: '도쿄도 시부야구',
      collectionPoint: '건물 1층 뒷문 오른쪽 녹색 수거망',
    },
  },
  shinjuku: {
    ja: {
      name: '東京都新宿区',
      collectionPoint: '入口左側の駐車スペース横の指定ごみ置き場',
    },
    en: {
      name: 'Shinjuku City, Tokyo',
      collectionPoint: 'Designated garbage area beside the parking space on the left of the entrance',
    },
    ko: {
      name: '도쿄도 신주쿠구',
      collectionPoint: '입구 왼쪽 주차 공간 옆 지정 쓰레기장',
    },
  },
  minato: {
    ja: {
      name: '東京都港区',
      collectionPoint: '建物裏側の青色資源回収ボックス付近',
    },
    en: {
      name: 'Minato City, Tokyo',
      collectionPoint: 'Near the blue recycling boxes behind the building',
    },
    ko: {
      name: '도쿄도 미나토구',
      collectionPoint: '건물 뒤쪽 파란색 재활용 수거함 구역',
    },
  },
}

export const wasteRules = [
  {
    id: 'pet-bottle',
    name: 'PET 塑料瓶',
    aliases: ['饮料瓶', '宝特瓶', 'ペットボトル'],
    type: '资源垃圾',
    icon: 'PET',
    days: { shibuya: '周三', shinjuku: '周二', minato: '周四' },
    steps: ['清空内容物', '简单冲洗', '取下瓶盖和标签', '压扁后放入透明袋'],
    wash: '需要简单冲洗',
    label: '标签需拆除',
    cap: '瓶盖需分离为塑料资源',
    bag: '透明或半透明垃圾袋',
    time: '当天 8:00 前',
    location: '公寓垃圾区资源回收箱旁',
    caution: '残留液体会导致回收拒收',
  },
  {
    id: 'burnable',
    name: '厨房厨余',
    aliases: ['剩菜', '可燃垃圾', '生ごみ'],
    type: '可燃垃圾',
    icon: '燃',
    days: { shibuya: '周一 / 周四', shinjuku: '周二 / 周五', minato: '周一 / 周四' },
    steps: ['沥干水分', '用纸包好异味强的厨余', '扎紧垃圾袋', '早上放到指定地点'],
    wash: '不需要清洗',
    label: '无标签处理',
    cap: '无瓶盖处理',
    bag: '透明或半透明可燃垃圾袋',
    time: '当天 8:00 前',
    location: '住宅楼一层垃圾投放点',
    caution: '不能前一天晚上投放，避免异味与散乱',
  },
  {
    id: 'spray-can',
    name: '喷雾罐',
    aliases: ['发胶', '瓦斯罐', 'スプレー缶'],
    type: '危险垃圾',
    icon: '危',
    days: { shibuya: '第 2 / 第 4 周五', shinjuku: '第 1 / 第 3 周三', minato: '第 2 周二' },
    steps: ['在通风处彻底用完', '不要自行打孔', '与其他垃圾分开', '标注“スプレー缶”后投放'],
    wash: '不需要清洗',
    label: '外包装可保留',
    cap: '塑料盖分开处理',
    bag: '透明袋，单独装袋',
    time: '当天 8:00 前',
    location: '危险垃圾指定收集点',
    caution: '残留气体有爆炸风险',
  },
  {
    id: 'battery',
    name: '干电池 / 小型电池',
    aliases: ['电池', '充电电池', '乾電池'],
    type: '有害垃圾',
    icon: '池',
    days: { shibuya: '每月第 1 周三', shinjuku: '每月第 2 周四', minato: '公共回收箱' },
    steps: ['用胶带贴住电极', '不要混入可燃垃圾', '放入电池回收盒', '膨胀电池咨询官方窗口'],
    wash: '不需要清洗',
    label: '无标签处理',
    cap: '无瓶盖处理',
    bag: '无需垃圾袋',
    time: '设施开放时间内',
    location: '区役所、便利店或公共设施回收盒',
    caution: '锂电池混入垃圾车可能引发火灾',
  },
]

export const wasteRuleText = {
  'pet-bottle': {
    ja: {
      name: 'PET ボトル',
      aliases: ['飲料ボトル', 'ペットボトル'],
      type: '資源ごみ',
      days: { shibuya: '水曜', shinjuku: '火曜', minato: '木曜' },
      steps: ['中身を空にする', '軽くすすぐ', 'キャップとラベルを外す', 'つぶして透明袋へ入れる'],
      wash: '軽くすすぐ',
      label: 'ラベルを外す',
      cap: 'キャップは分別',
      bag: '透明または半透明の袋',
      time: '当日 8:00 まで',
      location: 'マンションごみ置き場の資源回収箱付近',
      caution: '中身が残っていると回収されない場合があります',
    },
    en: {
      name: 'PET bottle',
      aliases: ['drink bottle', 'plastic bottle'],
      type: 'Recyclable',
      days: { shibuya: 'Wednesday', shinjuku: 'Tuesday', minato: 'Thursday' },
      steps: ['Empty the bottle', 'Rinse lightly', 'Remove cap and label', 'Crush and put in a clear bag'],
      wash: 'Rinse lightly',
      label: 'Remove label',
      cap: 'Separate cap',
      bag: 'Clear or translucent bag',
      time: 'By 8:00 on collection day',
      location: 'Near the recycling box in the building garbage area',
      caution: 'Liquid residue may cause rejection',
    },
    ko: {
      name: 'PET 병',
      aliases: ['음료병', '페트병'],
      type: '재활용 쓰레기',
      days: { shibuya: '수요일', shinjuku: '화요일', minato: '목요일' },
      steps: ['내용물 비우기', '가볍게 헹구기', '뚜껑과 라벨 분리', '압축 후 투명 봉투에 넣기'],
      wash: '가볍게 헹굼',
      label: '라벨 분리',
      cap: '뚜껑 분리',
      bag: '투명 또는 반투명 봉투',
      time: '수거일 8:00 전',
      location: '건물 쓰레기장 재활용 박스 근처',
      caution: '내용물이 남아 있으면 수거되지 않을 수 있습니다',
    },
  },
  burnable: {
    ja: {
      name: '生ごみ',
      aliases: ['残飯', '燃えるごみ'],
      type: '可燃ごみ',
      days: { shibuya: '月曜 / 木曜', shinjuku: '火曜 / 金曜', minato: '月曜 / 木曜' },
      steps: ['水気を切る', 'においが強いものは紙で包む', '袋をしっかり結ぶ', '朝に指定場所へ出す'],
      wash: '洗浄不要',
      label: 'ラベル処理なし',
      cap: 'キャップ処理なし',
      bag: '透明または半透明の可燃ごみ袋',
      time: '当日 8:00 まで',
      location: '建物 1 階のごみ置き場',
      caution: '前夜に出すとにおいや散乱の原因になります',
    },
    en: {
      name: 'Kitchen waste',
      aliases: ['leftovers', 'burnable garbage'],
      type: 'Burnable',
      days: { shibuya: 'Monday / Thursday', shinjuku: 'Tuesday / Friday', minato: 'Monday / Thursday' },
      steps: ['Drain water', 'Wrap strong-smelling waste in paper', 'Tie the bag tightly', 'Put out in the morning'],
      wash: 'No washing needed',
      label: 'No label handling',
      cap: 'No cap handling',
      bag: 'Clear or translucent burnable bag',
      time: 'By 8:00 on collection day',
      location: 'Ground-floor residential garbage point',
      caution: 'Do not put it out the previous night',
    },
    ko: {
      name: '음식물 쓰레기',
      aliases: ['남은 음식', '가연 쓰레기'],
      type: '가연 쓰레기',
      days: { shibuya: '월요일 / 목요일', shinjuku: '화요일 / 금요일', minato: '월요일 / 목요일' },
      steps: ['물기 제거', '냄새가 강한 것은 종이로 감싸기', '봉투를 단단히 묶기', '아침에 지정 장소 배출'],
      wash: '세척 불필요',
      label: '라벨 처리 없음',
      cap: '뚜껑 처리 없음',
      bag: '투명 또는 반투명 가연 쓰레기봉투',
      time: '수거일 8:00 전',
      location: '주거 건물 1층 쓰레기장',
      caution: '전날 밤 배출하면 냄새와 흩어짐의 원인이 됩니다',
    },
  },
  'spray-can': {
    ja: {
      name: 'スプレー缶',
      aliases: ['ヘアスプレー', 'ガス缶'],
      type: '危険ごみ',
      days: { shibuya: '第 2 / 第 4 金曜', shinjuku: '第 1 / 第 3 水曜', minato: '第 2 火曜' },
      steps: ['風通しの良い場所で使い切る', '自分で穴を開けない', '他のごみと分ける', 'スプレー缶と表示して出す'],
      wash: '洗浄不要',
      label: '外装はそのままで可',
      cap: 'プラスチックキャップは分別',
      bag: '透明袋で単独袋詰め',
      time: '当日 8:00 まで',
      location: '危険ごみ指定収集場所',
      caution: '残留ガスは爆発の危険があります',
    },
    en: {
      name: 'Spray can',
      aliases: ['hair spray', 'gas can'],
      type: 'Hazardous',
      days: { shibuya: '2nd / 4th Friday', shinjuku: '1st / 3rd Wednesday', minato: '2nd Tuesday' },
      steps: ['Use up in a ventilated place', 'Do not puncture it yourself', 'Keep separate from other garbage', 'Label it as spray can'],
      wash: 'No washing needed',
      label: 'Outer label can stay',
      cap: 'Separate plastic cap',
      bag: 'Clear bag, packed alone',
      time: 'By 8:00 on collection day',
      location: 'Designated hazardous garbage point',
      caution: 'Residual gas can explode',
    },
    ko: {
      name: '스프레이캔',
      aliases: ['헤어스프레이', '가스캔'],
      type: '위험 쓰레기',
      days: { shibuya: '둘째 / 넷째 금요일', shinjuku: '첫째 / 셋째 수요일', minato: '둘째 화요일' },
      steps: ['환기가 되는 곳에서 완전히 사용', '직접 구멍을 뚫지 않기', '다른 쓰레기와 분리', '스프레이캔 표시 후 배출'],
      wash: '세척 불필요',
      label: '외부 라벨 유지 가능',
      cap: '플라스틱 뚜껑 분리',
      bag: '투명 봉투에 단독 포장',
      time: '수거일 8:00 전',
      location: '위험 쓰레기 지정 수거 장소',
      caution: '잔류 가스는 폭발 위험이 있습니다',
    },
  },
  battery: {
    ja: {
      name: '乾電池 / 小型電池',
      aliases: ['電池', '充電池'],
      type: '有害ごみ',
      days: { shibuya: '毎月第 1 水曜', shinjuku: '毎月第 2 木曜', minato: '公共回収箱' },
      steps: ['電極にテープを貼る', '可燃ごみに混ぜない', '電池回収箱へ入れる', '膨張電池は窓口へ相談'],
      wash: '洗浄不要',
      label: 'ラベル処理なし',
      cap: 'キャップ処理なし',
      bag: '袋不要',
      time: '施設の開館時間内',
      location: '区役所、コンビニ、公共施設の回収箱',
      caution: 'リチウム電池の混入は火災につながります',
    },
    en: {
      name: 'Battery / small battery',
      aliases: ['battery', 'rechargeable battery'],
      type: 'Harmful waste',
      days: { shibuya: '1st Wednesday monthly', shinjuku: '2nd Thursday monthly', minato: 'Public collection box' },
      steps: ['Tape the terminals', 'Do not mix with burnable garbage', 'Place in a battery collection box', 'Ask the city office about swollen batteries'],
      wash: 'No washing needed',
      label: 'No label handling',
      cap: 'No cap handling',
      bag: 'No bag required',
      time: 'During facility hours',
      location: 'Collection boxes at city office, convenience stores, or public facilities',
      caution: 'Lithium batteries can cause garbage truck fires',
    },
    ko: {
      name: '건전지 / 소형 배터리',
      aliases: ['배터리', '충전지'],
      type: '유해 쓰레기',
      days: { shibuya: '매월 첫째 수요일', shinjuku: '매월 둘째 목요일', minato: '공공 회수함' },
      steps: ['전극에 테이프 붙이기', '가연 쓰레기와 섞지 않기', '배터리 회수함에 넣기', '부풀어 오른 배터리는 창구 상담'],
      wash: '세척 불필요',
      label: '라벨 처리 없음',
      cap: '뚜껑 처리 없음',
      bag: '봉투 불필요',
      time: '시설 운영 시간 내',
      location: '구청, 편의점, 공공시설 회수함',
      caution: '리튬 배터리는 쓰레기차 화재를 일으킬 수 있습니다',
    },
  },
}

export const cultureTips = [
  '防乌鸦网用于防止垃圾袋被翻开，投放后要完整盖回。',
  '多数地区不允许前一天晚上丢垃圾，以减少异味、噪音和散乱。',
  '透明垃圾袋让收集人员能快速确认是否混入错误分类。',
  '垃圾被贴警告退回时，通常需要重新分类后等下一次收集日。',
]

export const cultureTipsText = {
  ja: [
    '防鳥ネットはごみ袋が荒らされるのを防ぐためのものです。出した後は全体を覆ってください。',
    '多くの地域では、におい・騒音・散乱を防ぐため前夜のごみ出しを禁止しています。',
    '透明袋は収集員が分別ミスをすばやく確認するために役立ちます。',
    '警告シールで戻されたごみは、再分別して次の収集日に出す必要があります。',
  ],
  en: [
    'Crow nets help prevent garbage bags from being opened. Cover the bags fully after disposal.',
    'Many areas do not allow putting garbage out the night before to reduce odors, noise, and scattering.',
    'Clear bags help collectors quickly check whether items are sorted correctly.',
    'If a warning sticker is attached, re-sort the garbage and wait for the next collection day.',
  ],
  ko: [
    '까마귀 방지망은 쓰레기봉투가 흐트러지는 것을 막기 위한 것입니다. 배출 후 전체를 덮어 주세요.',
    '많은 지역은 냄새, 소음, 흩어짐을 줄이기 위해 전날 밤 배출을 금지합니다.',
    '투명 봉투는 수거원이 분류 오류를 빠르게 확인하는 데 도움이 됩니다.',
    '경고 스티커가 붙어 반려되면 다시 분류한 뒤 다음 수거일에 배출해야 합니다.',
  ],
}

export const officialSources = [
  { label: '涩谷区垃圾与资源分类页面', area: 'shibuya', freshness: '13 天前更新' },
  { label: '新宿区资源与垃圾收集日 PDF', area: 'shinjuku', freshness: '15 天前更新' },
  { label: '港区家庭垃圾分类指南', area: 'minato', freshness: '11 天前更新' },
]

export const officialSourceText = {
  shibuya: {
    ja: { label: '渋谷区 ごみと資源の分け方ページ', freshness: '13 日前更新' },
    en: { label: 'Shibuya City garbage and recycling guide', freshness: 'Updated 13 days ago' },
    ko: { label: '시부야구 쓰레기 및 재활용 분류 페이지', freshness: '13일 전 갱신' },
  },
  shinjuku: {
    ja: { label: '新宿区 資源・ごみ収集日 PDF', freshness: '15 日前更新' },
    en: { label: 'Shinjuku City recycling and garbage collection PDF', freshness: 'Updated 15 days ago' },
    ko: { label: '신주쿠구 재활용 및 쓰레기 수거일 PDF', freshness: '15일 전 갱신' },
  },
  minato: {
    ja: { label: '港区 家庭ごみ分別ガイド', freshness: '11 日前更新' },
    en: { label: 'Minato City household garbage sorting guide', freshness: 'Updated 11 days ago' },
    ko: { label: '미나토구 가정 쓰레기 분류 안내', freshness: '11일 전 갱신' },
  },
}

export const languageLabels = {
  zh: '中文',
  ja: '日本語',
  en: 'English',
  ko: '한국어',
}

export const qrPageProfiles = {
  guest: {
    title: 'Airbnb 住客垃圾说明',
    owner: 'Jinnan Stay Room 302',
    note: '请在退房前确认厨房和浴室的小垃圾已按分类放入对应袋子。',
    i18n: {
      ja: { title: 'Airbnb ゲスト向けごみ案内', note: 'チェックアウト前に、キッチンと浴室の小さなごみを分別して袋に入れてください。' },
      en: { title: 'Airbnb Guest Garbage Guide', note: 'Before checkout, sort small kitchen and bathroom trash into the correct bags.' },
      ko: { title: 'Airbnb 게스트 쓰레기 안내', note: '체크아웃 전 주방과 욕실의 작은 쓰레기를 분류해 알맞은 봉투에 넣어 주세요.' },
    },
  },
  shop: {
    title: '小型店铺垃圾说明',
    owner: 'Green Bento Shibuya',
    note: '营业垃圾请与家庭垃圾分开，纸箱压平后按资源日投放。',
    i18n: {
      ja: { title: '小規模店舗向けごみ案内', note: '事業ごみは家庭ごみと分け、段ボールは平らにして資源日に出してください。' },
      en: { title: 'Small Shop Garbage Guide', note: 'Keep business garbage separate from household garbage, and flatten cardboard for recycling day.' },
      ko: { title: '소형 매장 쓰레기 안내', note: '영업 쓰레기는 가정 쓰레기와 분리하고, 박스는 접어서 재활용일에 배출하세요.' },
    },
  },
  multi: {
    title: '多房源共用说明',
    owner: 'Tokyo Host Group',
    note: '不同房源可能有不同投放点，请以页面显示的照片和地址为准。',
    i18n: {
      ja: { title: '複数物件共通ごみ案内', note: '物件ごとにごみ置き場が異なる場合があります。写真と住所を確認してください。' },
      en: { title: 'Multi-Property Garbage Guide', note: 'Each property may have a different disposal point. Check the photos and address shown here.' },
      ko: { title: '여러 숙소 공통 쓰레기 안내', note: '숙소마다 배출 장소가 다를 수 있으니 사진과 주소를 확인하세요.' },
    },
  },
}

export const uiText = {
  zh: {
    appSubtitle: '日本垃圾分类助手',
    navToday: '今日垃圾',
    navSearch: '分类搜索',
    navQr: 'QR 店家页',
    navManagement: '资料管理',
    navSources: '官方来源',
    defaultReminder: '默认提醒',
    reminderTime: '前一天 21:00',
    on: '开',
    off: '关',
    heroEyebrow: 'MVP Phase 1 / Tokyo 23 Wards',
    heroTitle: '今天该丢什么垃圾，一眼看懂。',
    currentLocation: '当前位置',
    officialConfirmed: '官方资料已确认',
    autoLocated: '自动定位到町丁目',
    notification: '通知',
    reminderTitle: '前一天提醒',
    pushLabel: '推播',
    reminderSentence: ({ type, bag, time }) => `明晚会提醒：${type}，${bag}，${time} 投放。`,
    trustedData: '可信数据',
    dataUpdatedAt: '数据更新日',
    searchEyebrow: '垃圾分类搜索',
    searchTitle: '输入物品名称',
    searchPlaceholder: '例：塑料瓶、电池、喷雾罐',
    disposalInstructions: '处理说明',
    wash: '清洗',
    label: '标签',
    cap: '瓶盖',
    collectionDay: '收集日',
    disposalTime: '投放时间',
    place: '地点',
    management: '资料管理',
    commonWasteItems: '常用垃圾项目',
    use: '使用',
    delete: '删除',
    reuseStatus: '复用状态',
    currentGuide: '当前说明',
    managementNote: '资料管理里的「使用」会把项目加入当前说明、QR 页面预览和提醒文案，方便房东或店家快速切换说明内容。',
    appliedToast: (name) => `已将「${name}」加入当前垃圾说明。`,
    qrPage: 'B2B QR 页面',
    qrTitle: '房东 / 店家说明页',
    guestMode: 'Airbnb',
    shopMode: '店家',
    multiMode: '多房源',
    photoUpload: '垃圾区照片 · 0 / 3',
    photoUploadNote: '支持 JPG / PNG / WEBP，后端可接入压缩、方向校正与说明生成。',
    openPublicPage: '打开公开页',
    posterPdf: 'A4 海报 PDF',
    ingestionEyebrow: 'AI 自动资料获取流程',
    ingestionTitle: '官方网页 → 结构化规则 → 多语言复用',
    ingestionSteps: ['搜索官方网页', '抓取 PDF / HTML', 'AI 解析结构化', '翻译多语言', '写入数据库'],
    cultureEyebrow: '垃圾文化小知识',
    cultureTitle: '降低不安感的解释层',
    publicQrPage: 'Public QR Page',
    todayCanDispose: '今天可投放',
    todayWaste: '今日垃圾',
    beforeDisposal: '投放前确认',
    basicRules: '基本规则',
    publicRules: ['垃圾请在当天早上指定时间前投放。', '透明或半透明袋更容易被收集人员确认。', 'PET 瓶、瓶盖、标签通常需要分离。', '喷雾罐和电池不要混入普通可燃垃圾。'],
    ruleUpdatedAt: '规则更新时间',
    admin: '管理端',
  },
  ja: {
    appSubtitle: '日本のごみ分別アシスタント',
    navToday: '今日のごみ',
    navSearch: '分別検索',
    navQr: 'QR 店舗ページ',
    navManagement: 'データ管理',
    navSources: '公式情報',
    defaultReminder: '既定リマインダー',
    reminderTime: '前日 21:00',
    on: 'オン',
    off: 'オフ',
    heroEyebrow: 'MVP Phase 1 / 東京23区',
    heroTitle: '今日出せるごみを、すぐ確認。',
    currentLocation: '現在地',
    officialConfirmed: '公式情報確認済み',
    autoLocated: '町丁目まで自動判定',
    notification: '通知',
    reminderTitle: '前日リマインダー',
    pushLabel: '通知',
    reminderSentence: ({ type, bag, time }) => `明日の通知：${type}、${bag}、${time} に出してください。`,
    trustedData: '信頼できるデータ',
    dataUpdatedAt: 'データ更新日',
    searchEyebrow: 'ごみ分別検索',
    searchTitle: '品目名を入力',
    searchPlaceholder: '例：ペットボトル、電池、スプレー缶',
    disposalInstructions: '出し方',
    wash: '洗浄',
    label: 'ラベル',
    cap: 'キャップ',
    collectionDay: '収集日',
    disposalTime: '出す時間',
    place: '場所',
    management: 'データ管理',
    commonWasteItems: 'よく使うごみ項目',
    use: '使用',
    delete: '削除',
    reuseStatus: '反映状況',
    currentGuide: '現在の説明',
    managementNote: '「使用」を押すと、現在の説明、QR プレビュー、通知文にその項目を反映できます。',
    appliedToast: (name) => `「${name}」を現在のごみ説明に追加しました。`,
    qrPage: 'B2B QR ページ',
    qrTitle: 'ホスト / 店舗向け説明ページ',
    guestMode: 'Airbnb',
    shopMode: '店舗',
    multiMode: '複数物件',
    photoUpload: 'ごみ置き場写真 · 0 / 3',
    photoUploadNote: 'JPG / PNG / WEBP 対応。圧縮、向き補正、説明文生成を後続で接続できます。',
    openPublicPage: '公開ページを開く',
    posterPdf: 'A4 ポスター PDF',
    ingestionEyebrow: 'AI 公式情報取得フロー',
    ingestionTitle: '公式ページ → 構造化ルール → 多言語再利用',
    ingestionSteps: ['公式ページ検索', 'PDF / HTML 取得', 'AI 構造化', '多言語翻訳', 'DB 保存'],
    cultureEyebrow: 'ごみ文化メモ',
    cultureTitle: '不安を減らす説明',
    publicQrPage: '公開 QR ページ',
    todayCanDispose: '今日出せるごみ',
    todayWaste: '今日のごみ',
    beforeDisposal: '出す前の確認',
    basicRules: '基本ルール',
    publicRules: ['ごみは当日の朝、指定時間までに出してください。', '透明または半透明の袋を使うと確認しやすくなります。', 'PET ボトル、キャップ、ラベルは分ける場合があります。', 'スプレー缶と電池は普通ごみに混ぜないでください。'],
    ruleUpdatedAt: 'ルール更新日',
    admin: '管理端',
  },
  en: {
    appSubtitle: 'Japan garbage sorting assistant',
    navToday: 'Today',
    navSearch: 'Search',
    navQr: 'QR page',
    navManagement: 'Data',
    navSources: 'Sources',
    defaultReminder: 'Default reminder',
    reminderTime: 'Previous day 21:00',
    on: 'On',
    off: 'Off',
    heroEyebrow: 'MVP Phase 1 / Tokyo 23 Wards',
    heroTitle: 'Know what garbage goes out today.',
    currentLocation: 'Current area',
    officialConfirmed: 'Official source verified',
    autoLocated: 'Auto-detected to town block',
    notification: 'Notification',
    reminderTitle: 'Previous-day reminder',
    pushLabel: 'push',
    reminderSentence: ({ type, bag, time }) => `Tomorrow reminder: ${type}, ${bag}, put out by ${time}.`,
    trustedData: 'Trusted data',
    dataUpdatedAt: 'Data updated',
    searchEyebrow: 'Garbage sorting search',
    searchTitle: 'Enter item name',
    searchPlaceholder: 'e.g. bottle, battery, spray can',
    disposalInstructions: 'Disposal guide',
    wash: 'Wash',
    label: 'Label',
    cap: 'Cap',
    collectionDay: 'Collection day',
    disposalTime: 'Time',
    place: 'Place',
    management: 'Data management',
    commonWasteItems: 'Common waste items',
    use: 'Use',
    delete: 'Delete',
    reuseStatus: 'Applied state',
    currentGuide: 'Current guide',
    managementNote: 'Use applies the item to the current guide, QR preview, and reminder copy so hosts and shops can switch instructions quickly.',
    appliedToast: (name) => `Added "${name}" to the current garbage guide.`,
    qrPage: 'B2B QR page',
    qrTitle: 'Host / shop instruction page',
    guestMode: 'Airbnb',
    shopMode: 'Shop',
    multiMode: 'Multi-property',
    photoUpload: 'Garbage area photos · 0 / 3',
    photoUploadNote: 'Supports JPG / PNG / WEBP. Compression, orientation fix, and captions can be wired later.',
    openPublicPage: 'Open public page',
    posterPdf: 'A4 poster PDF',
    ingestionEyebrow: 'AI source ingestion flow',
    ingestionTitle: 'Official pages → structured rules → multilingual reuse',
    ingestionSteps: ['Search official pages', 'Fetch PDF / HTML', 'AI structure parse', 'Translate', 'Save to DB'],
    cultureEyebrow: 'Garbage culture notes',
    cultureTitle: 'Context that reduces uncertainty',
    publicQrPage: 'Public QR page',
    todayCanDispose: 'Can dispose today',
    todayWaste: 'Today’s garbage',
    beforeDisposal: 'Before disposal',
    basicRules: 'Basic rules',
    publicRules: ['Put garbage out on the morning of collection before the specified time.', 'Clear or translucent bags help collectors verify sorting.', 'PET bottles, caps, and labels often need to be separated.', 'Do not mix spray cans or batteries with ordinary burnable garbage.'],
    ruleUpdatedAt: 'Rule updated',
    admin: 'Admin',
  },
  ko: {
    appSubtitle: '일본 쓰레기 분리배출 도우미',
    navToday: '오늘 쓰레기',
    navSearch: '분류 검색',
    navQr: 'QR 페이지',
    navManagement: '데이터 관리',
    navSources: '공식 출처',
    defaultReminder: '기본 알림',
    reminderTime: '전날 21:00',
    on: '켜짐',
    off: '꺼짐',
    heroEyebrow: 'MVP Phase 1 / 도쿄 23구',
    heroTitle: '오늘 버릴 쓰레기를 바로 확인.',
    currentLocation: '현재 지역',
    officialConfirmed: '공식 자료 확인됨',
    autoLocated: '町丁目까지 자동 판정',
    notification: '알림',
    reminderTitle: '전날 알림',
    pushLabel: '푸시',
    reminderSentence: ({ type, bag, time }) => `내일 알림: ${type}, ${bag}, ${time}까지 배출.`,
    trustedData: '신뢰 데이터',
    dataUpdatedAt: '데이터 갱신일',
    searchEyebrow: '쓰레기 분류 검색',
    searchTitle: '품목명 입력',
    searchPlaceholder: '예: 페트병, 배터리, 스프레이캔',
    disposalInstructions: '배출 방법',
    wash: '세척',
    label: '라벨',
    cap: '뚜껑',
    collectionDay: '수거일',
    disposalTime: '배출 시간',
    place: '장소',
    management: '데이터 관리',
    commonWasteItems: '자주 쓰는 항목',
    use: '사용',
    delete: '삭제',
    reuseStatus: '적용 상태',
    currentGuide: '현재 안내',
    managementNote: '사용을 누르면 현재 안내, QR 미리보기, 알림 문구에 해당 항목이 적용됩니다.',
    appliedToast: (name) => `「${name}」을 현재 쓰레기 안내에 추가했습니다.`,
    qrPage: 'B2B QR 페이지',
    qrTitle: '호스트 / 매장 안내 페이지',
    guestMode: 'Airbnb',
    shopMode: '매장',
    multiMode: '여러 숙소',
    photoUpload: '쓰레기장 사진 · 0 / 3',
    photoUploadNote: 'JPG / PNG / WEBP 지원. 압축, 방향 보정, 설명 생성은 이후 연결할 수 있습니다.',
    openPublicPage: '공개 페이지 열기',
    posterPdf: 'A4 포스터 PDF',
    ingestionEyebrow: 'AI 공식 자료 수집 흐름',
    ingestionTitle: '공식 페이지 → 구조화 규칙 → 다국어 재사용',
    ingestionSteps: ['공식 페이지 검색', 'PDF / HTML 수집', 'AI 구조화', '다국어 번역', 'DB 저장'],
    cultureEyebrow: '쓰레기 문화 메모',
    cultureTitle: '불안을 줄이는 설명',
    publicQrPage: '공개 QR 페이지',
    todayCanDispose: '오늘 배출 가능',
    todayWaste: '오늘 쓰레기',
    beforeDisposal: '배출 전 확인',
    basicRules: '기본 규칙',
    publicRules: ['쓰레기는 수거 당일 아침 지정 시간 전까지 배출하세요.', '투명 또는 반투명 봉투는 분류 확인에 도움이 됩니다.', 'PET 병, 뚜껑, 라벨은 분리해야 할 수 있습니다.', '스프레이캔과 배터리는 일반 가연 쓰레기에 섞지 마세요.'],
    ruleUpdatedAt: '규칙 갱신일',
    admin: '관리',
  },
}
